---
- name: 'Install Nginx'
  become: yes
  apt:
    name: 'nginx'
    state: 'present'

- name: "Start Nginx"
  become: yes
  service:
    name: 'nginx'
    state: 'started'

- name: 'Debug Repository Dir'
  debug:
      msg: "repo_dir = {{ lookup('env','REPOSITORY_DIR') }}"

- name: 'Debug Nginx_Config_DFile'
  debug:
      msg: "nginx env = {{ lookup('env','NGINX_CONFIG_FILE') }}"

- name: 'Debug Nginx_Config Var'
  debug:
      msg: "nginx var = {{ nginx_config_file }}"

- name: 'Debug Workspace'
  debug:
      msg: "nginx var = {{ lookup('env','WORKSPACE') }}"

- name: 'Copy Nginx config file to sites-available'
  become: yes
  copy:
      src: "{{ lookup('env','REPOSITORY_DIR') }}/{{ nginx_config_file }}"
      dest: '/etc/nginx/sites-available/default_config.cfg'
  when: nginx_config_file | length > 0

- name: 'Create sysmlink sites-available to sites-enabled'
  become: yes
  file:
      src: '/etc/nginx/sites-available/default_config.cfg'
      dest: '/etc/nginx/sites-enabled/default'
      state: link
  when: nginx_config_file | length > 0

- name: 'Restart Nginx'
  become: yes
  service:
      name: nginx
      state: restarted