---
- name: 'Install Nginx'
  become: yes
  apt:
    name: 'nginx'
    state: 'present'

- name: "Start Nginx"
  become: yes
  service:
    name: 'nginx'
    state: 'started'

- name: 'Copy Nginx config file to sites-available'
  become: yes
  copy:
      src: "{{ REPOSITORY_DIR }}/{{ NGINX_CONFIG_FILE }}"
      dest: '/etc/nginx/sites-available/default_config.cfg'
  when: NGINX_CONFIG_FILE | length > 0

- name: 'Create sysmlink sites-available to sites-enabled'
  become: yes
  file:
      src: '/etc/nginx/sites-available/default_config.cfg'
      dest: '/etc/nginx/sites-enabled/default'
      state: link
  when: NGINX_CONFIG_FILE | length > 0

- name: 'Restart Nginx'
  become: yes
  service:
      name: nginx
      state: restarted