---
- name: 'Copy Golang Binary to Production Servers'
  become: yes
  copy:
      src: "{{ jenkins_workspace }}/{{ repository_dir }}/{{ repository_name }}"
      dest: '/usr/bin/{{ repository_name }}'

- name: 'Copy Service Init to Production Servers'
  become: yes
  copy:
      src: "{{ jenkins_workspace }}/{{ repository_dir }}/{{ init_config_file }}"
      dest: '/etc/systemd/system/{{ repository_name }}.service'

- name: 'Copy Socketmaster Binary to Production Servers'
  become: yes
  copy:
      src: "{{ jenkins_workspace }}/{{ socketmaster_file }}"
      dest: '/usr/bin/socketmaster'

- name: "Start Golang Service"
  become: yes
  service:
    name: 'testapp'
    state: 'started'

- name: 'Restart Golang Service'
  become: yes
  service:
      name: 'testapp'
      state: 'restarted'